image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - apk add --no-cache git

build:
  stage: build
  script:
    - git config --global http.version HTTP/1.1
    - git fetch --unshallow || true
    - git checkout $CI_COMMIT_REF_NAME

    - export NEW_VERSION=$(git describe --tags --match "v*" --always --dirty)

    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

    - docker build -t elviomixto/docker-graphql:$NEW_VERSION .
    - docker build -t elviomixto/docker-graphql:latest .

    - docker push elviomixto/docker-graphql:$NEW_VERSION
    - docker push elviomixto/docker-graphql:latest

only:
  - main
